-- NOTE: This file is auto generated by ./sql-generator

-- UserRepository.get
select
  "id",
  "name",
  "email",
  "createdAt",
  "updatedAt",
  "deletedAt",
  "isAdmin",
  "status",
  "shouldChangePassword"
from
  "users"
where
  "users"."id" = $1
  and "users"."deletedAt" is null

-- UserRepository.getAdmin
select
  "id",
  "name",
  "email",
  "createdAt",
  "updatedAt",
  "deletedAt",
  "isAdmin",
  "status",
  "shouldChangePassword"
from
  "users"
where
  "users"."isAdmin" = $1
  and "users"."deletedAt" is null

-- UserRepository.getByEmail
select
  "id",
  "name",
  "email",
  "createdAt",
  "updatedAt",
  "deletedAt",
  "isAdmin",
  "status",
  "shouldChangePassword"
from
  "users"
where
  "email" = $1
  and "users"."deletedAt" is null

-- UserRepository.getList (with deleted)
select
  "id",
  "name",
  "email",
  "createdAt",
  "updatedAt",
  "deletedAt",
  "isAdmin",
  "status",
  "shouldChangePassword"
from
  "users"
order by
  "createdAt" desc

-- UserRepository.getList (without deleted)
select
  "id",
  "name",
  "email",
  "createdAt",
  "updatedAt",
  "deletedAt",
  "isAdmin",
  "status",
  "shouldChangePassword"
from
  "users"
where
  "users"."deletedAt" is null
order by
  "createdAt" desc
