global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: api
    static_configs:
      - targets: ['server:8081']

  - job_name: microservices
    static_configs:
      - targets: ['server:8082']
