/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';
import { UserTable } from 'src/schemas/tables/user.table';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U> ? ColumnType<S, I | undefined, U> : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Migrations {
  id: Generated<number>;
  name: string;
  timestamp: Int8;
}

export interface Users {
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  email: string;
  firstName: Generated<string | null>;
  id: Generated<string>;
  isAdmin: Generated<boolean | null>;
  isFirstLoggedIn: Generated<boolean | null>;
  lastName: Generated<string | null>;
  password: string;
  salt: string;
  shouldChangePassword: Generated<boolean | null>;
}

export interface DB {
  migrations: Migrations;
  users: UserTable;
}
